// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wneqfhdifhuoyiqofygj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduZXFmaGRpZmh1b3lpcW9meWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTkwMDUsImV4cCI6MjA2MjE5NTAwNX0.uz916NnYck_VMIWpIVmuGvRP3HvSK-d2FWD4BsZ7p1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);